// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hycggwcoczwclmymbeth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5Y2dnd2NvY3p3Y2xteW1iZXRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MTkwMjQsImV4cCI6MjA2NzA5NTAyNH0.uaAHXJweT_YcW0rbdDEV-nAzsJWTFibtCm4YJ30snVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});